import os, tempfile
 
code = []
 
code.append('import os, tempfile')
code.append('from flask import Flask, request, jsonify')
code.append('from flask_cors import CORS')
code.append('from flask_sqlalchemy import SQLAlchemy')
code.append('from flask_jwt_extended import create_access_token, JWTManager, jwt_required, get_jwt_identity')
code.append('from werkzeug.security import generate_password_hash, check_password_hash')
code.append('from datetime import timedelta')
code.append('')
code.append('app = Flask(__name__)')
code.append('CORS(app)')
code.append("db_path = os.path.join(os.environ.get('TEMP', tempfile.gettempdir()), 'rag_course.db')")
code.append("app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + db_path.replace('\\\\', '/')")
code.append("app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False")
code.append("app.config['JWT_SECRET_KEY'] = 'course-rag-system-secret-2026'")
code.append("app.config['JWT_ACCESS_TOKEN_EXPIRES'] = timedelta(days=7)")
code.append('')
code.append('db = SQLAlchemy(app)')
code.append('jwt = JWTManager(app)')
code.append('')
code.append('class User(db.Model):')
code.append("    __tablename__ = 'users'")
code.append('    id = db.Column(db.Integer, primary_key=True)')
code.append("    username = db.Column(db.String(80), unique=True, nullable=False)")
code.append("    password = db.Column(db.String(200), nullable=False)")
code.append("    role = db.Column(db.String(20), nullable=False, default='student')")
code.append('    created_at = db.Column(db.DateTime, server_default=db.func.now())')
code.append('')
code.append('class StudentQuestion(db.Model):')
code.append("    __tablename__ = 'student_questions'")
code.append('    id = db.Column(db.Integer, primary_key=True)')
code.append("    student_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)")
code.append("    student_name = db.Column(db.String(80), nullable=False)")
code.append('    course_id = db.Column(db.Integer, nullable=True)')
code.append("    course_name = db.Column(db.String(200), nullable=True)")
code.append("    title = db.Column(db.String(200), nullable=False)")
code.append('    content = db.Column(db.Text, nullable=False)')
code.append('    answer = db.Column(db.Text, nullable=True)')
code.append("    status = db.Column(db.String(20), default='pending')")
code.append('    created_at = db.Column(db.DateTime, server_default=db.func.now())')
code.append('')
code.append("with app.app_context():")
code.append('    db.create_all()')
code.append("    if not User.query.filter_by(username='admin').first():")
code.append("        db.session.add(User(username='admin', password=generate_password_hash('admin123'), role='admin'))")
code.append("        db.session.add(User(username='teacher1', password=generate_password_hash('teacher123'), role='teacher'))")
code.append("        db.session.add(User(username='student1', password=generate_password_hash('student123'), role='student'))")
code.append('        db.session.commit()')
code.append('')
code.append("@app.route('/api/auth/register', methods=['POST'])")
code.append('def register():')
code.append('    data = request.get_json()')
code.append("    if not data or not data.get('username') or not data.get('password'):")
code.append("        return jsonify({'message': 'err'}), 400")
code.append("    if User.query.filter_by(username=data['username']).first():")
code.append("        return jsonify({'message': 'exists'}), 409")
code.append("    user = User(username=data['username'], password=generate_password_hash(data['password']), role=data.get('role', 'student'))")
code.append('    db.session.add(user)')
code.append('    db.session.commit()')
code.append("    return jsonify({'message': 'ok'}), 201")
code.append('')
code.append("@app.route('/api/auth/login', methods=['POST'])")
code.append('def login():')
code.append('    data = request.get_json()')
code.append("    if not data or not data.get('username') or not data.get('password'):")
code.append("        return jsonify({'message': 'err'}), 400")
code.append("    user = User.query.filter_by(username=data['username']).first()")
code.append("    if not user or not check_password_hash(user.password, data['password']):")
code.append("        return jsonify({'message': 'bad'}), 401")
code.append('    token = create_access_token(identity=str(user.id))')
code.append("    return jsonify({'token': token, 'user': {'id': user.id, 'username': user.username, 'role': user.role}})")
code.append('')
code.append("@app.route('/api/ask-teacher', methods=['POST'])")
code.append('@jwt_required()')
code.append('def ask_teacher():')
code.append('    user_id = int(get_jwt_identity())')
code.append('    user = User.query.get(user_id)')
code.append("    if not user or user.role != 'student':")
code.append("        return jsonify({'message': 'forbid'}), 403")
code.append('    data = request.get_json()')
code.append("    q = StudentQuestion(student_id=user.id, student_name=user.username, course_id=data.get('course_id'), course_name=data.get('course_name', ''), title=data['title'], content=data['content'], status='pending')")
code.append('    db.session.add(q)')
code.append('    db.session.commit()')
code.append("    return jsonify({'message': 'ok', 'id': q.id}), 201")
code.append('')
code.append("@app.route('/api/ask-teacher/mine', methods=['GET'])")
code.append('@jwt_required()')
code.append('def my_questions():')
code.append('    user_id = int(get_jwt_identity())')
code.append("    qs = StudentQuestion.query.filter_by(student_id=user_id).order_by(StudentQuestion.created_at.desc()).all()")
code.append("    return jsonify({'questions': [{'id': q.id, 'title': q.title, 'content': q.content, 'course_name': q.course_name, 'status': q.status, 'answer': q.answer, 'created_at': str(q.created_at)} for q in qs]})")
code.append('')
code.append("@app.route('/api/ask-teacher', methods=['GET'])")
code.append('@jwt_required()')
code.append('def teacher_questions():')
code.append("    qs = StudentQuestion.query.order_by(StudentQuestion.created_at.desc()).all()")
code.append("    return jsonify({'questions': [{'id': q.id, 'student_name': q.student_name, 'title': q.title, 'content': q.content, 'course_name': q.course_name, 'status': q.status, 'answer': q.answer, 'created_at': str(q.created_at)} for q in qs]})")
code.append('')
code.append("@app.route('/api/ask-teacher/<int:qid>/reply', methods=['POST'])")
code.append('@jwt_required()')
code.append('def reply_question(qid):')
code.append('    q = StudentQuestion.query.get(qid)')
code.append("    if not q: return jsonify({'message': 'nf'}), 404")
code.append('    data = request.get_json()')
code.append("    q.answer = data['answer']")
code.append("    q.status = 'answered'")
code.append('    db.session.commit()')
code.append("    return jsonify({'message': 'ok'})")
code.append('')
code.append("@app.route('/api/teacher/stats', methods=['GET'])")
code.append('@jwt_required()')
code.append('def teacher_stats():')
code.append("    return jsonify({'courses': 0, 'courseware': 0, 'questions': 0, 'knowledge_points': 0})")
code.append('')
code.append("@app.route('/api/admin/stats', methods=['GET'])")
code.append('@jwt_required()')
code.append('def admin_stats():)
code.append("    return jsonify({'users': User.query.count(), 'courses': 0, 'questions': 0, 'knowledge_points': 0})")
code.append('')
code.append("@app.route('/api/admin/users', methods=['GET'])")
code.append('@jwt_required()')
code.append('def admin_users():)
code.append("    users = User.query.all()")
code.append("    return jsonify({'users': [{'id': u.id, 'username': u.username, 'role': u.role, 'created_at': str(u.created_at)} for u in users]})")
code.append('')
code.append("@app.route('/api/admin/users/<int:user_id>/role', methods=['PUT'])")
code.append('@jwt_required()')
code.append('def update_role(user_id):")
code.append('    data = request.get_json()')
code.append('    user = User.query.get(user_id)')
code.append("    if not user: return jsonify({'message': 'nf'}), 404")
code.append("    user.role = data['role']")
code.append("    db.session.commit()")
code.append("    return jsonify({'message': 'ok'})")
code.append('')
code.append("@app.route('/api/admin/users/<int:user_id>', methods=['DELETE'])")
code.append('@jwt_required()')
code.append('def del_user(user_id):")
code.append('    user = User.query.get(user_id)')
code.append("    if not user: return jsonify({'message': 'nf'}), 404")
code.append("    db.session.delete(user)")
code.append("    db.session.commit()")
code.append("    return jsonify({'message': 'ok'})")
code.append('')
code.append("@app.route('/api/courses', methods=['GET'])")
code.append('@jwt_required()')
code.append('def get_courses():')
code.append("    return jsonify({'courses': []})")
code.append('')
code.append("@app.route('/api/teacher/courses', methods=['GET'])")
code.append('@jwt_required()')
code.append('def teacher_courses():')
code.append("    return jsonify({'courses': []})")
code.append('')
code.append("@app.route('/api/teacher/courses', methods=['POST'])")
code.append('@jwt_required()')
code.append('def create_course():)
code.append("    return jsonify({'message': 'ok'})")
code.append('')
code.append("@app.route('/api/teacher/statistics', methods=['GET'])")
code.append('@jwt_required()')
code.append('def teacher_statistics():)
code.append("    return jsonify({'questions': []})")
code.append('')
code.append("@app.route('/api/admin/courses', methods=['GET'])")
code.append('@jwt_required()')
code.append('def admin_courses():)
code.append("    return jsonify({'courses': []})")
code.append('')
code.append("if __name__ == '__main__':")
code.append('    app.run(host="0.0.0.0", port=5000, debug=True)')
 
target = r'D:\RAG\RAG-based-AI-Course\back-end\app.py'
with open(target, 'w', encoding='utf-8') as f:
    f.write('\n'.join(code))
print('Created:', target, len('\n'.join(code)), 'bytes')

